apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wg-access-server.fullname" . }}
  labels:
    {{- include "wg-access-server.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{- if .Values.config.wireguard }}
{{ toYaml .Values.config.wireguard | indent 4 }}
{{- end }}
