{{- $fullName := include "wg-access-server.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-web
  labels:
    {{- include "wg-access-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "wg-access-server.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-wireguard
  labels:
    {{- include "wg-access-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wireguard.service.type }}
{{- if .Values.wireguard.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.wireguard.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: 51820
      targetPort: 51820
      protocol: UDP
      name: wireguard
  selector:
    {{- include "wg-access-server.selectorLabels" . | nindent 4 }}
